name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Clean Install
        run: rm -rf node_modules && rm -f package-lock.json && rm -f bun.lockb

      - name: Install Dependencies
        run: |
          bun install --frozen-lockfile=false
        env:
          NODE_ENV: development

      - name: Run Tests
        run: bun test
        env:
          NODE_ENV: test

      - name: Report Status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Tests passed successfully"
          else
            echo "❌ Tests failed"
          fi
