name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Clear Bun Cache
        run: bun pm cache rm

      - name: Use Alternate Registry
        run: bun config set registry https://registry.yarnpkg.com

      - name: Install Dependencies with Retry
        run: |
          for i in {1..3}; do bun install --force && break || sleep 10; done
        env:
          NODE_ENV: development

      - name: Run Tests
        run: bun test
        env:
          NODE_ENV: test

      - name: Report Status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Tests passed successfully"
          else
            echo "❌ Tests failed"
          fi
